version: "3.9"

services:
  test1Shankar:
    image: rfiready.co:5000/test1Shankar:${TAG}
    build:
      context: ../../../
      dockerfile: ./services/test1/docker/Dockerfile
      args:
        NODE_ENV: prod
        SERVICE_NAME: test1Shankar
        PORT: 123456
    working_dir: /app
    deploy:
      replicas: 2
      restart_policy:
        delay: 10s
        condition: on-failure
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
        failure_action: rollback
    ports:
      - 123456:123456
    networks:
      - api-service
    volumes:
      - type: volume
        source: test1Shankarlog
        target: /service/test1Shankar/log
        volume:
          nocopy: true

networks:
  api-service:
    external: true
volumes:
  test1Shankarlog:
    driver_opts:
      type: nfs4
      o: "addr=172.31.84.217,nolock,rw"
      device: ":/root/nfs/test1Shankar/log"
