version: "3.9"

services:
  test1Shankar:
    build:
      context: ../../../
      dockerfile: ./services/test1/docker/Dockerfile.dev
      args:
        NODE_ENV: prod
        SERVICE_NAME: test1Shankar
        PORT: 123456
    working_dir: /app
    ports:
      - 123456:123456
    volumes:
      - ../../operation:/app/services/test1
