version: "3.9"

services:
  operation:
    build:
      context: ../../../
      dockerfile: ./services/operation/docker/Dockerfile.Dev
      args:
        NODE_ENV: prod
        SERVICE_NAME: operation
        PORT: 3333
    working_dir: /app
    ports:
      - 3333:3333
    networks:
      - api-service
    volumes:
      - ../../operation:/app/services/operation

networks:
  api-service:
    external: true
