version: 0.0
os: linux
files:
 - source: .
   destination: /home/ec2-user/src
hooks:
  # AfterInstall:
  #  - location: /home/ec2-user/generated_backend_deploy.sh
  #    timeout: 300
  #    runas: root
  ApplicationStart:
    - location: /bins/deploy.sh
      timeout: 300
      runas: root
