name: RFIReady CICD
on:
  push

jobs:
  CICD:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.10.0]
    env:
      COMMIT_MSG: ${{ github.event.head_commit.message }}${{ github.event.pull_request.title }}
    steps:
      # - uses: actions/checkout@v3
      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: ${{ matrix.node-version }}
      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: npx nx affected --target=lint --parallel=3

      # - uses: actions/cache@v2
      #   with:
      #     path: '**/node_modules'
      #     key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      # - name: Install packages
      #   run: yarn install

      # - name: Check Affected
      #   run: yarn nx affected:apps

      # - name: ConfigureAWS
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ env.AWS_REGION }}

      # - name: Deploy
      #   run: |
      #     aws deploy create-deployment \
      #     --application-name ${{ env.APP_NAME }} \
      #     --deployment-group-name ${{ env.DEPLOY_GROUP }} \
      #     --deployment-config-name ${{ env.DEPLOY_CONFIG }} \
      #     --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
