name: CICD
on:
  release:
    types: [published]
  push:
    branches:
      - main

jobs:
  CD:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.10.0]
    steps:
      - name: Install packages
        run: sudo apt-get install -y git

      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn install

      - name: Get project version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Setup docker image version
        run: |
          echo ${{ steps.package-version.outputs.current-version}}
          export TAG=${{ steps.package-version.outputs.current-version}}

      - name: Push docker images
        run: yarn nx push-deploylist cicd

      - name: ConfigureAWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy
        run: |
          aws deploy create-deployment \
          --application-name ${{ env.APP_NAME }} \
          --deployment-group-name ${{ env.DEPLOY_GROUP }} \
          --deployment-config-name ${{ env.DEPLOY_CONFIG }} \
          --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
