name: RFIReady CICD
on:
  push


jobs:
  TEST:
    runs-on: ubuntu-latest
    env:
      COMMIT_MSG: ${{ github.event.head_commit.message }}${{ github.event.pull_request.title }}
    steps:
      - uses: actions/checkout@v3

      - name: testing
        run: |
          echo ${{ github.event.head_commit.message }}
