name: Release
on:
  push:
    branches:
      - main

jobs:
  Release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.10.0]
    steps:
      - name: Install packages
        run: sudo apt-get install -y git

      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}


      # - name: Conventional Changelog Action
      #   id: changelog
      #   uses: TriPSs/conventional-changelog-action@v3
      #   with:
      #     github-token: ${{ secrets.github_token }}
      #     output-file: "false"
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Check version
        run: echo ${{ steps.package-version.outputs.current-version}}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.package-version.outputs.current-version}}
          release_name: ${{ steps.package-version.outputs.current-version}}
          body_path: CHANGELOG.md
